
<?php 
    //todo: move logic to the block
    list($min,$max) = $this->_filter->getMinMaxPriceInt(); 
    list($from,$to) = explode(',', $this->_filter->getActiveState()); 
    
    $from = floor(max($from, $min));
    
    if ($to) {
        $to   = ceil(min($to, $max));
    } else {
        $to = $max;
    }
    
    if ($to<1 && $from<1) {
        $to = $max;
    }

	//Set the slider width
    $width = 170;
    
    if ($max) {
        if ($max == $min) {
            $firstOffset = 0;
            $secondOffset = $width;
        } else  {
			$firstOffset  = ($from-$min)*$width/($max-$min);
			$secondOffset = ($to-$min)*$width/($max-$min);
        }
    } else  {
			$firstOffset  = 0;
			$secondOffset = 0;
    }
?>
<ol>
    <li>
<?php if ($to != $from) :?> 
<?php echo $this->__('Від:')?> 
<input type="text" id="price_range_from<?php echo $this->_filter->getRequestVar()?>" class="sliderValue" data-index="0" value="<?php echo $from?>" />
<?php echo $this->__('До:')?> 
<input id="price_range_to<?php echo $this->_filter->getRequestVar()?>" type="text" class="sliderValue" data-index="0" value="<?php echo $to?>" />
<?php else:?>
<?php echo $this->__('Value:')?> 
<?php echo $this->getSymbol()?><span id="price_range_from<?php echo $this->_filter->getRequestVar()?>"><?php echo $from?></span>
<?php endif;?> 

<?php if ($to != $from) :?> 
<div id="fme_layered_price_slider<?php echo $this->_filter->getRequestVar()?>" class="price_slider">
    <div class="handle selected" style="left:<?php echo $firstOffset?>px"></div>
    <div class="handle" style="left:<?php echo $secondOffset?>px"></div>
  </div>
<?php endif;?> 

<?php if ($to != $from) :?> 
<script type="text/javascript">
    var slider = create_price_slider(<?php echo $width.', '.$firstOffset.', '.$secondOffset.', '.$min.', '.$max.',"'.$this->_filter->getRequestVar()?>");
</script>
<?php endif;?> 
    </li>
</ol>

<script>
jQuery("input.sliderValue").change(function() {	
	var sKey = 'price';
    var numFrom = roundPrice(jQuery('#price_range_from' + sKey).val()),
            numTo = roundPrice(jQuery('#price_range_to' + sKey).val());

    if ((numFrom < 0.01 && numTo < 0.01) || numFrom < 0 || numTo < 0)
        return;

    fme_layered_add_params('p', 1, 1);
    fme_layered_add_params(sKey, numFrom + ',' + numTo, true);
    fme_layered_make_request();
});
</script>


