<?php 
$items        = $this->getFiltersArray();
$displayStyle = $this->getColumnsNum(); 
?>
<?/*<ol>
<?php if ($displayStyle <=1): // one column ?>
    <?php foreach ($items as $_item): ?>
        <li><?php echo $_item?></li>
    <?php endforeach ?>
<?php endif ?>
</ol>*/?>

<script>
function clickToFilter(element)
{
	id = jQuery(element).find('a').attr('id');
	document.getElementById(id).click()
	//console.log(jQuery(element).find('a').attr('id'));
}
</script>
<?php if ($displayStyle <=1): // one column ?>
    <?php foreach ($items as $key => $_item): ?>
		<?php echo $_item?>
    <?php endforeach ?>
<?php endif ?>
