<?php

$step_counter = 1;
$helper = Mage::helper('onestepcheckout/checkout');

?>

<section class="s-order-checkout">
<?php if(!$this->canCheckout() || !$this->validateMinimumAmount()): ?>
    <?php if($this->settings['checkout_title']): ?>
        <h1 class="onestepcheckout-title"><?php echo $this->settings['checkout_title']; ?></h1>
    <?php endif; ?>

    <?php if($this->canCheckout() && !$this->validateMinimumAmount()): ?>
    <p><?php echo Mage::getStoreConfig('sales/minimum_order/description'); ?></p>
    <p><a href="<?php echo $this->getUrl(''); ?>"><?php echo $this->__('Back to homepage'); ?></a></p>
    <?php else: ?>
    <p><?php echo $this->__('You need to have products in your cart to checkout, and your cart is empty.'); ?></p>
    <p><a href="<?php echo $this->getUrl(''); ?>"><?php echo $this->__('Back to homepage'); ?></a></p>
    <?php endif; ?>
<?php else: ?>

<form id="onestepcheckout-form" method="post" action="<?php echo $this->getUrl('onestepcheckout', array('_secure'=>true)); ?>">
<fieldset class="group-select" style="margin: 0;">
<?php /*if(!$this->isCustomerLoggedIn() && $helper->showLoginLink()): ?>
    <p class="onestepcheckout-login-link">
        <a id="onestepcheckout-login-link" href="javascript:void(0);"><?php echo $this->__('Already registered? Click here to login.'); ?></a>
    </p>
<?php endif; */?>

<?php if(isset($this->formErrors['unknown_source_error'])): ?>
<div class="onestepcheckout-error">
    <?php echo $this->formErrors['unknown_source_error']; ?>
</div>
<?php endif; ?>

<div class="onestepcheckout-threecolumns checkoutcontainer onestepcheckout-skin-<?php echo $this->settings['skin']; ?> <?php if(Mage::helper('onestepcheckout')->isEnterprise()): ?>onestepcheckout-enterprise<?php endif; ?>">
    <div class="onestepcheckout-column-left">
        <div id="billing_address">
            <script type="text/javascript">
            var billing = new Billing();

            </script>
            <ul>
                <li>
                    <p class="onestepcheckout-numbers onestepcheckout-numbers-<?php echo $step_counter++; ?>"><?php echo $this->__('Billing address'); ?></p>
                        <?php if(isset($this->formErrors['billing_error']) && count($this->formErrors['billing_errors']) > 0): ?>
                        <div class="onestepcheckout-error">
                            <?php echo $this->__('Please check red fields below and try again.'); ?>
                        </div>
                        <?php endif; ?>
                </li>


                <?php if ($this->customerHasAddresses()): ?>
                <li>
                    <label for="billing-address-select"><?php echo $this->__('Select a billing address from your address book or enter a new address.') ?></label>
                    <div class="input-box">
                        <?php echo $this->getAddressesHtmlSelect('billing') ?>
                    </div>
                </li>
                <?php endif; ?>
                <li>
                    <div>
                        <ul id="billing_address_list" <?php echo (($this->customerHasAddresses() && !$this->getNewAddressSelectValueOnError('billing')) ? 'style = "display:none"' : false ); ?>>
                            <?php echo $this->getChildHtml('billing_address');?>
                            <?php $addressAttributes = $this->getChild('customer_form_billing_address_user_defined_attributes');?>
                            <?php if ($addressAttributes): ?>
                                <?php $addressAttributes->setEntity($this->getQuote()->getBillingAddress())->setEntityType('customer_address');?>
                                <?php $addressAttributes->setFieldIdFormat('billing:%1$s')->setFieldNameFormat('billing[%1$s]');?>
                                <?php echo $addressAttributes->setExcludeFileAttributes(true)->setShowContainer(false)->toHtml()?>
                            <?php endif;?>
                            <?php $customerAttributes = $this->getChild('customer_form_customer_user_defined_attributes');?>
                            <?php if ($customerAttributes): ?>
                                <?php $customerAttributes->setEntityModelClass('customer/customer')->setFieldIdFormat('billing:%1$s');?>
                                <?php $customerAttributes->setFieldNameFormat('billing[%1$s]')->setShowContainer(false);?>
                                <?php echo $customerAttributes->setExcludeFileAttributes(true)->toHtml()?>
                            <?php endif;?>
                        </ul>
                    </div>
                </li>
                <li>

                 <input type="hidden" name="billing[use_for_shipping]" id="billing:use_for_shipping_yes" value="1" />

                </li>
            </ul>
        </div>
</div>

    <div class="onestepcheckout-column-middle">

        <?php if(!$this->isVirtual()): ?>
            <?php if(Mage::getStoreConfig('onestepcheckout/general/hide_shipping_method')):?>
                <?php if(isset($this->formErrors['shipping_method']) && $this->formErrors['shipping_method']): ?>
                    <div class="onestepcheckout-error onestepcheckout-shipment-method-error">
                        <?php echo $this->__('Please choose a shipping method.'); ?>
                    </div>
                <?php endif; ?>
                <?php echo $this->getChildHtml('choose-shipping-method'); ?>
            <?php else:?>
                <div class="onestepcheckout-shipping-method">
                    <p class="onestepcheckout-numbers onestepcheckout-numbers-<?php echo $step_counter++; ?>"><?php echo $this->__('Shipping method'); ?></p>

                    <?php if(isset($this->formErrors['shipping_method']) && $this->formErrors['shipping_method']): ?>
                    <div class="onestepcheckout-error onestepcheckout-shipment-method-error">
                        <?php echo $this->__('Please choose a shipping method.'); ?>
                    </div>
                    <?php endif; ?>

                    <div class="onestepcheckout-shipping-method-block">
                        <?php echo $this->getChildHtml('choose-shipping-method'); ?>
                    </div>
                </div>
            <?php endif; ?>
        <?php endif; ?>

        <?php if(Mage::getStoreConfig('onestepcheckout/general/hide_payment_method')):?>
            <?php if(!empty($this->formErrors['payment_method'])): ?>
            <div class="onestepcheckout-error onestepcheckout-payment-method-error">
                <?php echo $this->__('Please choose a payment method.'); ?>
            </div>
            <?php endif; ?>
            <?php if(!empty($this->formErrors['payment_method_error'])): ?>
                <div class="onestepcheckout-error onestepcheckout-payment-method-error">
                    <?php echo $this->__('Please enter valid details below.'); ?>
                </div>
            <?php endif; ?>
            <?php echo $this->getChildHtml('choose-payment-method'); ?>
        <?php else: ?>
            <p class="onestepcheckout-numbers onestepcheckout-numbers-<?php echo $step_counter++; ?>"><?php echo $this->__('Payment method'); ?></p>
            <?php if(isset($this->formErrors['payment_method']) && $this->formErrors['payment_method']): ?>
                <div class="onestepcheckout-error onestepcheckout-payment-method-error">
                    <?php echo $this->__('Please choose a payment method.'); ?>
                </div>
            <?php else: ?>
                <?php if(isset($this->formErrors['payment_method_error'])): ?>
                    <div class="onestepcheckout-error onestepcheckout-payment-method-error">
                        <?php echo $this->__('Please enter valid details below.'); ?>
                    </div>
                <?php endif; ?>
            <?php endif; ?>

            <?php echo $this->getChildHtml('choose-payment-method'); ?>

            <div class="tool-tip" id="payment-tool-tip" style="display:none;">
                <div class="btn-close">
                    <a href="javascript:void(0);" id="payment-tool-tip-close"><img src="<?php echo $this->getSkinUrl('images/btn_window_close.gif') ?>" alt="<?php echo $this->__('Close') ?>" /></a>
                </div>
                <div class="block-content">
                <img src="<?php echo $this->getSkinUrl('images/cvv.gif') ?>" alt="<?php echo $this->__('Card Verification Number Visual Reference') ?>" />
                </div>
            </div>
        <?php endif; ?>
    </div>

    <div class="onestepcheckout-column-right">

        <p class="onestepcheckout-numbers onestepcheckout-numbers-4"><?php echo $this->__('Review your order'); ?></p>

        <div id="onestepcheckoutSummary" class="onestepcheckout-summary">
            <?php echo $this->getChildHtml('summary'); ?>
        </div>

        <div class="onestepcheckout-place-order-wrapper">
            <button type="button" title="<?php echo $this->__('Place order now'); ?>" id="onestepcheckout-place-order" class="large orange onestepcheckout-button onestepcheckout-place-order" onclick="javascript:void(0);"><span><span><?php echo $this->__('Place order now'); ?></span></span></button>
        </div>
    </div>
    <div style="clear: both;">&nbsp;</div>
</div>
</fieldset>
</form>

<?php if(!$this->isCustomerLoggedIn() && $helper->showLoginLink()): ?>
    <?php echo $this->getChildHtml('login-popup'); ?>
<?php endif; ?>

<?php if($helper->isValidateEmail()): ?>
<script>
$('billing:email').observe('blur', function(e)    {
    var url = '<?php echo $this->getUrl('onestepcheckout/ajax/check_email', array('_secure'=>true)); ?>';
    var email = e.element().getValue();
    var parameters = { email: email };

    new Ajax.Request(url, {
        parameters: parameters,
        onComplete: function(response)  {
            if(response.status == 200)  {
                var result = response.responseText.evalJSON().result;
                if(result == 'invalid') {
                    $('onestepcheckout-email-error-message').update('<?php echo $this->__('Invalid email address.'); ?>');
                    $('onestepcheckout-email-error').show();
                }
                else if(result == 'exists') {
                    <?php if($this->settings['registration_order_without_password']): ?>
                    // Remove the password fields if the email exists in database
                    $('onestepcheckout-li-password').hide();
                    <?php endif; ?>
                    $('onestepcheckout-email-error-message').update('<?php echo $this->__('Email address already registered. Please <a href="javascript:void(0);" onclick="login_popup.show(); return false;">login now</a> or use a different email address.'); ?>');
                    $('onestepcheckout-email-error').show();
                    $('id_onestepcheckout_username').value = email;
                }
                else    {
                    $('onestepcheckout-email-error').hide();
                    $('onestepcheckout-li-password').show();
                }
            }
        }
    })

});
Validation.add('validate-email', '<?php echo $this->__('This is a required field.') ?>', function(v) {
    var url = '<?php echo $this->getUrl('onestepcheckout/ajax/check_email', array('_secure'=>true)); ?>';
    var email = v;
    var parameters = { email: email };
    var value = Validation.get('IsEmpty').test(v) || /^([a-z0-9,!\#\$%&'\*\+\/=\?\^_`\{\|\}~-]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+(\.([a-z0-9,!\#\$%&'\*\+\/=\?\^_`\{\|\}~-]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+)*@([a-z0-9-]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+(\.([a-z0-9-]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+)*\.(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]){2,})$/i.test(v)

    new Ajax.Request(url, {
        parameters: parameters,
        asynchronous: false,
        onComplete: function(response)  {
            if(response.status == 200)  {
                var result = response.responseText.evalJSON().result;
                if(result == 'invalid') {
                    value = false;
                } else if(result == 'exists') {
                    <?php if($this->settings['registration_order_without_password']): ?>
                    $('onestepcheckout-li-password').hide();
                    <?php endif; ?>
                    $('onestepcheckout-email-error-message').update('<?php echo $this->__('Email address already registered. Please <a href="javascript:void(0);" onclick="login_popup.show(); return false;">login now</a> or use a different email address.'); ?>');
                    $('onestepcheckout-email-error').show();
                    $('id_onestepcheckout_username').value = email;
                    value =  false;
                }
            }
        }
    })
    return value;
});
</script>
<?php endif; ?>

<?php if($this->settings['enable_terms']): ?>
<div id="onestepcheckout-toc-popup" style="display: none;">

    <div class="onestepcheckout-popup-wrapper">
        <div class="onestepcheckout-popup-wrapper-inner">
            <h1><?php echo $this->settings['terms_title']; ?></h1>

            <div class="onestepcheckout-toc-terms">
                <?php echo $this->settings['terms_contents']; ?>
            </div>

            <p class="close"><a href="javascript:void(0);"><?php echo $this->__('Close'); ?></a></p>
        </div>
    </div>
    <div class="onestepcheckout-popup-footer">&nbsp;</div>
</div>
<script>
Event.observe(window, 'load', function() {

    var termsPopup = new Control.Modal($('onestepcheckout-toc-popup'), {
        overlayOpacity: 0.65,
        fade: true,
        fadeDuration: 0.3
    });

    $('onestepcheckout-toc-link').observe('click', function(e) {
        e.preventDefault();
        termsPopup.open();
    });

    $$('div#onestepcheckout-toc-popup p.close a').invoke('observe', 'click', function(e) {
        e.preventDefault();
        termsPopup.close();
    });

});

/*
var popup;
Event.observe(window, 'load', function() {
    popup = new OneStepCheckout_Popup('onestepcheckout-toc-popup','onestepcheckout-toc-link', 'div#onestepcheckout-toc-popup p.close a');
});
*/
</script>
<?php endif; ?>





<script>
<?php if($this->hasFormErrors()): ?>
if($$('div.input-error').length > 0) {
    var input = $$('div.input-error')[0].select('input');
    if(input.length == 1)   {
        input[0].focus();
    }
}
<?php endif; ?>
</script>

<?php if(!$this->settings['exclude_region']): ?>
<script type="text/javascript">countryRegions = <?php echo $this->helper('directory')->getRegionJson() ?></script>
<script type="text/javascript">
//<![CDATA[
    var billingRegionUpdater = new RegionUpdater('billing:country_id', 'billing:region', 'billing:region_id', countryRegions, undefined, 'billing:postcode');

    <?php if($this->settings['enable_different_shipping'] && !$this->isVirtual()): ?>
    var shippingRegionUpdater = new RegionUpdater('shipping:country_id', 'shipping:region', 'shipping:region_id', countryRegions, undefined, 'shipping:postcode');
    <?php endif; ?>
//]]>
</script>
<?php endif; ?>


<script type="text/javascript">

Event.observe(window, 'load', function() {
    if ($$('div.shopping-cart-totals').length == 1) {
    }
    else    {

        already_placing_order = false;
        review = false;
        reviewmodal = false;

        /* Handle place order click event */
        $$('.onestepcheckout-place-order').each(function(elem){
            elem.observe('click', function(e)   {
                Event.stop(e);

               // First validate the form
                var form = new VarienForm('onestepcheckout-form');

                if(!form.validator.validate())  {
                    Event.stop(e);
                } else {

                    if(!already_placing_order && $$('.loading-ajax').length <= 0 ) {
                    <?php if(!empty($helper->settings['addressreview']['enable_addressreview'])):?>
                        var addressTemplates = {
                            shipping: '<?php echo str_replace("\r", '', str_replace("\n", '', $helper->settings['addressreview']['shipping_template']));?>',
                            billing: '<?php echo str_replace("\r", '', str_replace("\n", '', $helper->settings['addressreview']['billing_template']));?>'
                        };
                        addressPreview(addressTemplates, 'addressreview');
                        if(!review){
                            review = true;
                            if(!reviewmodal){
                                reviewmodal = new Control.Modal($('addressreview'),{
                                    overlayOpacity: 0.75,
                                    className: 'modal',
                                    fade: true,
                                    closeOnClick: false
                                });
                            }
                            reviewmodal.open();
                            reviewmodal.observe('beforeClose',function(){
                                review = false;
                            });
                            return true;
                            Event.stop(e);
                        } else {
                            reviewmodal.close();
                        }
                    <?php endif;?>
                        already_placing_order = true;

                        var submitelement = $('onestepcheckout-place-order');

                        var loaderelement = new Element('div').
                            addClassName('onestepcheckout-place-order-loading').
                            update('<img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif'); ?>" />&nbsp;&nbsp;<?php echo $this->__('Please wait, processing your order...'); ?>');

                        submitelement.parentNode.appendChild(loaderelement);

                        /* Disable button to avoid multiple clicks */
                        submitelement.removeClassName('orange').addClassName('grey');
                        submitelement.disabled = true;

                        /* Submit the form */
                        $('onestepcheckout-form').submit();
                    }
                }
            });
        });


        // This is a separate page
        var url = '<?php echo $this->getUrl('onestepcheckout/ajax/set_methods_separate', array('_secure'=>true)); ?>';
        var update_payments = <?php echo $this->settings['enable_update_payment_on_shipping'] ? 'true' : 'false'; ?>;

        $$('dl.shipment-methods input').invoke('observe', 'click', get_separate_save_methods_function(url, update_payments));
        $$('div.payment-methods input[name="payment\[method\]"]').invoke('observe', 'click', get_separate_save_methods_function(url));

        $$('div.payment-methods input[name="payment\[method\]"]').invoke('observe', 'click', function() {
            $$('div.onestepcheckout-payment-method-error').each(function(item) {
                new Effect.Fade(item);
            });
        });

        $$('dl.shipment-methods input').invoke('observe', 'click', function() {
            $$('div.onestepcheckout-shipment-method-error').each(function(item) {
                new Effect.Fade(item);
            });
        });

        var has_hidden_terms = false;

        if($('id_accept_terms') != null)    {

            $('id_accept_terms').observe('click', function(e)   {
                var element = e.element();

                if(element.checked) {
                    $$('div.onestepcheckout-terms-error').each(function(item) {
                        new Effect.Fade(item);
                        has_hidden_terms = true;
                    });
                }
                else    {
                    if(has_hidden_terms)    {
                        $$('div.onestepcheckout-terms-error').each(function(item) {
                            new Effect.Appear(item);
                            has_hidden_terms = false;
                        });
                    }
                }
            });
        }
    }

    var form = $('onestepcheckout-form');

    /* Highlight selected payment method if one set */
    if($RF(form, 'payment[method]') != null)    {
        try {
            var payment_method = $RF(form, 'payment[method]');
            $('container_payment_method_' + payment_method).show();
            $('payment_form_' + payment_method).show();
        } catch(err)    {

        }
    }

    /* Set default shipping method if not set */
    if($RF(form, 'shipping_method') == null)    {
        try {
            var method = '<?php echo $this->_getDefaultShippingMethod(); ?>';
            if(method != '')    {
                $('s_method_' + method).checked = true;
                get_separate_save_methods_function(url);
            }
        } catch(err)    {

        }
    }
   //submit what's available on load
   get_separate_save_methods_function(url)();

<?php if($this->differentShippingAvailable()): ?>
    $('billing:use_for_shipping_yes').observe('click', function(e)  {
        var element = e.element();
        if(element.checked){
            $('shipping_address').hide();
        } else {
            if($('shipping-address-select') && $('shipping-address-select').value == ''){
                $('shipping_address_list').show()
            }
            $('shipping_address').show();
            <?php if(!$this->isCustomerLoggedIn()):?>
            $('shipping_address_list').show()
            <?php endif;?>
            <?php if($this->isCustomerLoggedIn()):?>
            if(!$('shipping-address-select') && $('shipping_address_list').getStyle('display')=='none'){
                $('shipping_address_list').show()
            }
            <?php endif;?>
        }

        <?php if($this->settings['enable_ajax_save_billing']): ?>
        get_save_billing_function('<?php echo $this->getUrl('onestepcheckout/ajax/save_billing', array('_secure'=>true)); ?>', '<?php echo $this->getUrl('onestepcheckout/ajax/set_methods_separate', array('_secure'=>true)); ?>', <?php echo $this->settings['enable_update_payment_on_shipping'] ? 'true' : 'false'; ?>, true)();
        <?php endif; ?>

    });
    <?php endif; ?>
    <?php
        $triggers = Mage::getStoreConfig('onestepcheckout/ajax_update/ajax_save_billing_fields');
        if(!empty($triggers)){
            $triggers = str_replace('country', 'country_id', $triggers);
            $triggers = str_replace('state/region', 'region_id', $triggers);
            $triggers = explode(',',$triggers);
            if(in_array('region_id',$triggers)){
                $triggers[] = 'region';
            }
        }
    ?>

    <?php if(Mage::getStoreConfig('onestepcheckout/ajax_update/enable_ajax_save_billing') && !empty($triggers)):?>

        var url_save_billing = '<?php echo $this->getUrl('onestepcheckout/ajax/save_billing', array('_secure'=>true)); ?>';
        var url_set_methods = '<?php echo $this->getUrl('onestepcheckout/ajax/set_methods_separate', array('_secure'=>true)); ?>';
        var update_payments = <?php echo $this->settings['enable_update_payment_on_shipping'] ? 'true' : 'false'; ?>;
        var update_on_initial = false;

        var euvat = $('euvat_action_validate_taxvat');

        if(euvat !== null){
            euvat.observe('click', get_save_billing_function(url_save_billing, url_set_methods, update_payments, true));
        }

        var euvatid = $('billing:vat_id');

        if(euvatid !== null){
            euvatid.observe('click', get_save_billing_function(url_save_billing, url_set_methods, update_payments, true));
        }

        triggers = ['<?php echo implode ('\',\'',$triggers)?>'];
        btriggered = [];
        striggered = [];

        <?php
        foreach($triggers as $value){
            echo (($this->getQuote()->getBillingAddress()->getData($value)) ? 'btriggered.push(\'billing:'.$value.'\');' : '');
            echo (($this->getQuote()->getShippingAddress()->getData($value)) ? 'striggered.push(\'shipping:'.$value.'\');' : '');
        }
        ?>


        bcountry_id = $('billing:country_id');
        if(bcountry_id){
            if(bcountry_id.getValue()){
                if(!btriggered.include('billing:country_id')){
                    btriggered.push('billing:country_id');
                }
            }
        }
        scountry_id = $('shipping:country_id');
        if(scountry_id){
            if(scountry_id.getValue()){
                if(!striggered.include('shipping:country_id')){
                    striggered.push('shipping:country_id');
                }
            }
        }

        batriggered = false;
        satriggered = false;

        changeTimer = false;
        changeInterval = 1000;

        triggers.each(function(item){
            var belement = $('billing:'+item);
            if(belement){
                belement.observe('change', function(e){
                    var element = e.element();
                    var id = element.id;
                    var tagname = element.tagName;
                    if(tagname === 'SELECT'){
                        clearTimeout(changeTimer);
                        changeTimer = setTimeout(bcallbackEvent, changeInterval, id);
                    } else {
                        bcallbackEvent(id);
                    }
                });
            }

            var selement = $('shipping:'+item);
            if(selement){
                selement.observe('change', function(e){
                    var element = e.element();
                    var id = element.id;
                    var tagname = element.tagName;
                    if(tagname === 'SELECT'){
                        clearTimeout(changeTimer);
                        changeTimer = setTimeout(scallbackEvent, changeInterval, id);
                    } else {
                        scallbackEvent(id);
                    }
                });
            }
        });

        function scallbackEvent (id){
            if(!striggered.include(id)){
                striggered.push(id);
            }
            if(striggered.length >= triggers.length-1){
                satriggered = true;
            }
            get_save_billing_function(url_save_billing, url_set_methods, update_payments, satriggered)();
        }


        function bcallbackEvent (id){
            if(!btriggered.include(id)){
                btriggered.push(id);
            }
            if(btriggered.length >= triggers.length-1){
                batriggered = true;
            }
            get_save_billing_function(url_save_billing, url_set_methods, update_payments, batriggered)();
        }


        <?php if($this->isCustomerLoggedIn()):?>
            var bselect = $('billing-address-select');
            var sselect = $('shipping-address-select');
            if(bselect){
                bselect.observe('change', get_save_billing_function(url_save_billing, url_set_methods, update_payments, true));
            }
            if(sselect){
                sselect.observe('change', get_save_billing_function(url_save_billing, url_set_methods, update_payments, true));
            }
        <?php endif;?>

    <?php endif; ?>

});

if($('payment-tool-tip-close')){
    Event.observe($('payment-tool-tip-close'), 'click', toggleToolTip);
}

</script>


<?php endif; ?>

<div id="onestepcheckout_popup_overlay" style="display: none;">&nbsp;</div>


<div id="loading-process" style="display: none;"></div>
</section>