<?php
   $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
?>
<section class="carousel-stock">
	<div class="inner">
				<h3 class="pop_top"><?php echo $this->__('Популярні товари') ?></h3>
				<div class="items">
<?php if(!$_productCollection->count()): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
    <?php $_collectionSize = $_productCollection->count() ?>
    <?php $_columnCount = $this->getColumnCount(); ?>
    <?php foreach ($_productCollection as $_product): ?>
            
			
				<div class="item">
					<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>">
						<div class="cont">
							<div class="cont-img">
								<img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(280); ?>" width="280" height="290" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
							</div>
							<div class="info">
								<h3><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></h3>
								<p><?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?></p>
							</div>
						</div>
						<?php echo $this->getPriceHtml($_product, true) ?>
						<div class="duration">
						<?php if($_product->isSaleable()): ?>
                        <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="btn blue" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>'); return false;"><?php echo $this->__('В кошик') ?></button>
						<span class="icon">
								<?php echo $this->__('В наявності') ?>
						</span>
						<?php else: ?>
							<p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
						<?php endif; ?>
						</div>
					</a>
				</div>
        <?php endforeach ?>
<?php endif; ?>						
											
		</div>
	</div>
</section>